#
# sprd_camera_pd.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

#
# Source List
#
KO_MODULE_NAME := sprd_camsys_pw_domain
KO_MODULE_SRC  :=

ifeq ($(strip $(BSP_KERNEL_VERSION)),unisoc-kernel)
KO_MODULE_PATH := $(srctree)/$(src)
else
KO_MODULE_PATH := $(src)
endif

ADAPT_DIR := $(BSP_BOARD_CAMERA_MODULE_ISP_ADAPT_VERSION)

KO_MODULE_SRC += $(wildcard $(KO_MODULE_PATH)/kernel/*.c)

#
# Build Options
#
ccflags-y += -I$(KO_MODULE_PATH)/../os_adapt/linux

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(KO_MODULE_PATH)/%.c,%.o,$(KO_MODULE_SRC))
