# SPDX-FileCopyrightText: 2015 Spreadtrum Communications (Shanghai) Co., Ltd
# SPDX-FileCopyrightText: 2016 Unisoc (Shanghai) Technologies Co., Ltd
# SPDX-License-Identifier: GPL-2.0-only

#
# snd-soc-tfa98xx.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please use these predefined name for keeping code:
#   KO_MODULE_NAME KO_MODULE_PATH KO_MODULE_SRC
#

#
# Source List
#
KO_MODULE_NAME := snd-soc-tfa98xx
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

COMPILE_TO_MODULE = n
DEVICE_TYPE_DIGITAL = n
PLATFORM_TYPE = sprd
EXTRA_CFLAGS += $(call cc-option,-Wno-date-time,)
EXTRA_CFLAGS += -I$(src)/inc
EXTRA_CFLAGS += -Wenum-conversion -Werror -Wuninitialized

ccflags-y += -I$(KO_MODULE_PATH)

obj-m := $(KO_MODULE_NAME).o

SPRD_CARD_COMMON := \
        src/tfa98xx.o \
        src/tfa_container.o \
        src/tfa_dsp.o \
        src/tfa_init.o

$(KO_MODULE_NAME)-y += $(SPRD_CARD_COMMON)


# Comment it if the only object file has the same name with module
#$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
